import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "../../components/templates/Footer";
import ToastProvider from "./templates/ToastProvider";
import "react-toastify/dist/ReactToastify.css";
import LoginBtn from "./login/LoginBtn";
import LogoutBtn from "./login/LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        {session ? (
          <span>
            {session.user.name} <LogoutBtn />
          </span>
        ) : (
          <LoginBtn />
        )}
        {children}
        <Footer />
      </body>
    </html>
  );
}
